services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-h", "db", "-U", "$$POSTGRES_USER", "--password", "$$POSTGRES_PASSWORD" ]
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  soldera-production:
    build: .
    volumes:
      - .:/code
    ports:
      - "80:8000"
      - "443:8443"
    depends_on:
      - db